using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;
using EdiFabric.Core.Model.Edi.ErrorContexts;
using EdiFabric.Core.Model.Edi.X12;
using EdiFabric.Framework.Writers;
using EdiFabric.Rules.HIPAA_5010;

namespace EdiFabric.Sdk.Hipaa
{
    /// <summary>
    /// Runs all write samples
    /// Check Output windows for debug data
    /// </summary>
    class WriteSamples
    {
        public static void Run()
        {
            WriteSingleClaimToStream();           
        }

        /// <summary>
        /// Generate and write claim to a stream
        /// </summary>
        static void WriteSingleClaimToStream()
        {
            Debug.WriteLine("******************************");
            Debug.WriteLine(MethodBase.GetCurrentMethod().Name);
            Debug.WriteLine("******************************");

            //  1.  Construct the claim message with data from database, service or domain objects\logic.
            var claim = CreateClaim("00000001");

            //  2.  Validate it to ensure the object adheres to the rule
            //  Always skip trailer validation because all trailers are automatically generated by the writer
            MessageErrorContext errorContext;
            if (claim.IsValid(out errorContext, true))
            {
                Debug.WriteLine("Message {0} with control number {1} is valid.", errorContext.Name, errorContext.ControlNumber);

                //  3.  Write to a stream
                using (var stream = new MemoryStream())
                {
                    //  4.  Use CRLF(new line) as segment postfix for clarity
                    //  Always agree postfixes and separators with the trading partner
                    using (var writer = new X12Writer(stream, Encoding.Default, Environment.NewLine))
                    {
                        //  5.  Begin with ISA segment
                        writer.Write(CreateIsa("000011111"));
                        //  6.  Follow up with GS segment
                        writer.Write(CreateGs("111111111"));
                        //  7.  Write all transactions
                        //  Batch up as many as needed
                        writer.Write(claim);
                        //  No need to close any of the above
                    }

                    Debug.Write(LoadString(stream));
                }
            }
            else
            {
                //  The claim is invalid
                //  Report it back to the sender, log, etc.

                //  Inspect MessageErrorContext for the validation errors
                var errors = errorContext.Flatten();

                Debug.WriteLine("Message {0} with control number {1} is invalid with errors:", errorContext.Name, errorContext.ControlNumber);
                foreach (var error in errors)
                {
                    Debug.WriteLine(error);
                }
            }
        }

        /// <summary>
        /// Sample claim
        /// </summary>
        static TS837P CreateClaim(string controlNumber)
        {
            var result = new TS837P();

            result.ST = new ST();
            result.ST.TransactionSetIdentifierCode_01 = "837";
            result.ST.TransactionSetControlNumber_02 = controlNumber.PadLeft(9, '0');
            result.ST.ImplementationConventionPreference_03 = "005010X222A1";

            result.BeginningofHierarchicalTransaction = new BHT_BeginningofHierarchicalTransaction();
            result.BeginningofHierarchicalTransaction.BHT01 = "0019";
            result.BeginningofHierarchicalTransaction.BHT02 = "00";
            result.BeginningofHierarchicalTransaction.BHT03 = "010";
            result.BeginningofHierarchicalTransaction.BHT04 = "20170617";
            result.BeginningofHierarchicalTransaction.BHT05 = "1741";
            result.BeginningofHierarchicalTransaction.BHT06 = "CH";

            result.AllNM1 = new All_NM1_TS837P();
            result.AllNM1.Loop1000A = new Loop_1000A_TS837P();

            result.AllNM1.Loop1000A.SubmitterName = new NM1_SubmitterName();
            result.AllNM1.Loop1000A.SubmitterName.NM101 = "41";
            result.AllNM1.Loop1000A.SubmitterName.NM102 = "2";
            result.AllNM1.Loop1000A.SubmitterName.NM103 = "SUBMITTER";
            result.AllNM1.Loop1000A.SubmitterName.NM108 = "46";
            result.AllNM1.Loop1000A.SubmitterName.NM109 = "ABC123";

            
            result.AllNM1.Loop1000A.SubmitterEDIContactInformation = new List<PER_BillingProviderContactInformation>();
            var per1 = new PER_BillingProviderContactInformation();
            per1.PER01 = "IC";
            per1.PER02 = "BOB SMITH";
            per1.PER03 = "TE";
            per1.PER04 = "4805551212";
            result.AllNM1.Loop1000A.SubmitterEDIContactInformation.Add(per1);

            result.AllNM1.Loop1000B = new Loop_1000B_TS837P();

            result.AllNM1.Loop1000B.ReceiverName = new NM1_ReceiverName();
            result.AllNM1.Loop1000B.ReceiverName.NM101 = "40";
            result.AllNM1.Loop1000B.ReceiverName.NM102 = "2";
            result.AllNM1.Loop1000B.ReceiverName.NM103 = "RECEIVER";
            result.AllNM1.Loop1000B.ReceiverName.NM108 = "46";
            result.AllNM1.Loop1000B.ReceiverName.NM109 = "44556";

            result.Loop2000A = new List<Loop_2000A_TS837P>();
            var loop2000A1 = new Loop_2000A_TS837P();

            loop2000A1.BillingProviderHierarchicalLevel = new HL_BillingProviderHierarchicalLevel();
            loop2000A1.BillingProviderHierarchicalLevel.HL01 = "1";
            loop2000A1.BillingProviderHierarchicalLevel.HL03 = "20";
            loop2000A1.BillingProviderHierarchicalLevel.HL04 = "1";

            loop2000A1.AllNM1 = new All_NM1_2_TS837P();
            loop2000A1.AllNM1.Loop2010AA = new Loop_2010AA_TS837P();
            loop2000A1.AllNM1.Loop2010AA.BillingProviderName = new NM1_BillingProviderName();
            loop2000A1.AllNM1.Loop2010AA.BillingProviderName.NM101 = "85";
            loop2000A1.AllNM1.Loop2010AA.BillingProviderName.NM102 = "2";
            loop2000A1.AllNM1.Loop2010AA.BillingProviderName.NM103 = "BILLING PROVIDER";
            loop2000A1.AllNM1.Loop2010AA.BillingProviderName.NM108 = "XX";
            loop2000A1.AllNM1.Loop2010AA.BillingProviderName.NM109 = "1122334455";

            loop2000A1.AllNM1.Loop2010AA.BillingProviderAddress = new N3_AmbulanceDrop();
            loop2000A1.AllNM1.Loop2010AA.BillingProviderAddress.N301 = "1234 SOME ROAD";

            loop2000A1.AllNM1.Loop2010AA.BillingProviderCity = new N4_AmbulanceDrop();
            loop2000A1.AllNM1.Loop2010AA.BillingProviderCity.N401 = "CHICAGO";
            loop2000A1.AllNM1.Loop2010AA.BillingProviderCity.N402 = "IL";
            loop2000A1.AllNM1.Loop2010AA.BillingProviderCity.N403 = "606739999";

            loop2000A1.AllNM1.Loop2010AA.AllREF = new All_REF_TS837P();
            loop2000A1.AllNM1.Loop2010AA.AllREF.BillingProviderTaxIdentification = new REF_BillingProviderTaxIdentification();
            loop2000A1.AllNM1.Loop2010AA.AllREF.BillingProviderTaxIdentification.REF01 = "EI";
            loop2000A1.AllNM1.Loop2010AA.AllREF.BillingProviderTaxIdentification.REF02 = "999999999";

            loop2000A1.Loop2000B = new List<Loop_2000B_TS837P>();

            var loop2000B1 = new Loop_2000B_TS837P();
            loop2000B1.SubscriberHierarchicalLevel = new HL_SubscriberHierarchicalLevel();
            loop2000B1.SubscriberHierarchicalLevel.HL01 = "2";
            loop2000B1.SubscriberHierarchicalLevel.HL02 = "1";
            loop2000B1.SubscriberHierarchicalLevel.HL03 = "22";
            loop2000B1.SubscriberHierarchicalLevel.HL04 = "0";

            loop2000B1.SubscriberInformation = new SBR_SubscriberInformation();
            loop2000B1.SubscriberInformation.SBR01 = "P";
            loop2000B1.SubscriberInformation.SBR02 = "18";
            loop2000B1.SubscriberInformation.SBR09 = "12";

            loop2000B1.AllNM1 = new All_NM1_3_TS837P();
            loop2000B1.AllNM1.Loop2010BA = new Loop_2010BA_TS837P();
            loop2000B1.AllNM1.Loop2010BA.SubscriberName = new NM1_SubscriberName();
            loop2000B1.AllNM1.Loop2010BA.SubscriberName.NM101 = "IL";
            loop2000B1.AllNM1.Loop2010BA.SubscriberName.NM102 = "1";
            loop2000B1.AllNM1.Loop2010BA.SubscriberName.NM103 = "BLOGGS";
            loop2000B1.AllNM1.Loop2010BA.SubscriberName.NM104 = "JOE";
            loop2000B1.AllNM1.Loop2010BA.SubscriberName.NM108 = "MI";
            loop2000B1.AllNM1.Loop2010BA.SubscriberName.NM109 = "1234567890";

            loop2000B1.AllNM1.Loop2010BA.SubscriberAddress = new N3_AmbulanceDrop();
            loop2000B1.AllNM1.Loop2010BA.SubscriberAddress.N301 = "1 SOME BLVD";

            loop2000B1.AllNM1.Loop2010BA.SubscriberCity = new N4_AmbulanceDrop();
            loop2000B1.AllNM1.Loop2010BA.SubscriberCity.N401 = "CHICAGO";
            loop2000B1.AllNM1.Loop2010BA.SubscriberCity.N402 = "IL";
            loop2000B1.AllNM1.Loop2010BA.SubscriberCity.N403 = "606129998";

            loop2000B1.AllNM1.Loop2010BA.SubscriberDemographicInformation = new DMG_PatientDemographicInformation();
            loop2000B1.AllNM1.Loop2010BA.SubscriberDemographicInformation.DMG01 = "D8";
            loop2000B1.AllNM1.Loop2010BA.SubscriberDemographicInformation.DMG02 = "19570111";
            loop2000B1.AllNM1.Loop2010BA.SubscriberDemographicInformation.DMG03 = "M";

            loop2000B1.AllNM1.Loop2010BB = new Loop_2010BB_TS837P();
            loop2000B1.AllNM1.Loop2010BB.PayerName = new NM1_OtherPayerName();
            loop2000B1.AllNM1.Loop2010BB.PayerName.NM101 = "PR";
            loop2000B1.AllNM1.Loop2010BB.PayerName.NM102 = "2";
            loop2000B1.AllNM1.Loop2010BB.PayerName.NM103 = "PAYER";
            loop2000B1.AllNM1.Loop2010BB.PayerName.NM108 = "PI";
            loop2000B1.AllNM1.Loop2010BB.PayerName.NM109 = "12345";

            loop2000B1.AllNM1.Loop2010BB.PayerAddress = new N3_AmbulanceDrop();
            loop2000B1.AllNM1.Loop2010BB.PayerAddress.N301 = "1 PAYER WAY";

            loop2000B1.AllNM1.Loop2010BB.PayerCity = new N4_AmbulanceDrop();
            loop2000B1.AllNM1.Loop2010BB.PayerCity.N401 = "ST LOUIS";
            loop2000B1.AllNM1.Loop2010BB.PayerCity.N402 = "MO";
            loop2000B1.AllNM1.Loop2010BB.PayerCity.N403 = "212441850";

            loop2000B1.AllNM1.Loop2010BB.AllREF = new All_REF_4_TS837P();
            loop2000B1.AllNM1.Loop2010BB.AllREF.PayerSecondaryIdentification = new List<REF_OtherPayerSecondaryIdentifier>();
            var refPayer1 = new REF_OtherPayerSecondaryIdentifier();
            refPayer1.REF01 = "2U";
            refPayer1.REF02 = "W1014";

            loop2000B1.AllNM1.Loop2010BB.AllREF.PayerSecondaryIdentification.Add(refPayer1);
            
            loop2000B1.Loop2300 = new List<Loop_2300_2_TS837P>();
            var loop23001 = new Loop_2300_2_TS837P();
            loop23001.ClaimInformation = new CLM_ClaimInformation();
            loop23001.ClaimInformation.CLM01 = "1000A";
            loop23001.ClaimInformation.CLM02 = "140";
            loop23001.ClaimInformation.CLM05 = new C023_HealthCareServiceLocationInformation();
            loop23001.ClaimInformation.CLM05.C02301 = "19";
            loop23001.ClaimInformation.CLM05.C02302 = "B";
            loop23001.ClaimInformation.CLM05.C02303 = "1";
            loop23001.ClaimInformation.CLM06 = "Y";
            loop23001.ClaimInformation.CLM07 = "A";
            loop23001.ClaimInformation.CLM08 = "Y";
            loop23001.ClaimInformation.CLM09 = "Y";

            loop23001.AllHI = new All_HI_2_TS837P();
            loop23001.AllHI.HealthCareDiagnosisCode = new HI_HealthCareDiagnosisCode();
            loop23001.AllHI.HealthCareDiagnosisCode.HI01 = new C022_HealthCareCodeInformation_6();
            loop23001.AllHI.HealthCareDiagnosisCode.HI01.C02201 = "ABK";
            loop23001.AllHI.HealthCareDiagnosisCode.HI01.C02202 = "I10";

            loop23001.Loop2400 = new List<Loop_2400_2_TS837P>();
            var loop24001 = new Loop_2400_2_TS837P();

            loop24001.ServiceLineNumber = new LX_ServiceLineNumber();
            loop24001.ServiceLineNumber.LX01 = "1";

            loop24001.ProfessionalService = new SV1_ProfessionalService();
            loop24001.ProfessionalService.SV101 = new C003_CompositeMedicalProcedureIdentifier_2();
            loop24001.ProfessionalService.SV101.C00301 = "HC";
            loop24001.ProfessionalService.SV101.C00302 = "99213";
            loop24001.ProfessionalService.SV102 = "140";
            loop24001.ProfessionalService.SV103 = "UN";
            loop24001.ProfessionalService.SV104 = "1";
            loop24001.ProfessionalService.SV107 = new C004_CompositeDiagnosisCodePointer();
            loop24001.ProfessionalService.SV107.C00401 = "1";

            loop24001.AllDTP = new All_DTP_2_TS837P();
            loop24001.AllDTP.Date = new DTP_Date_18();
            loop24001.AllDTP.Date.DTP01 = "472";
            loop24001.AllDTP.Date.DTP02 = "D8";
            loop24001.AllDTP.Date.DTP03 = "20151124";

            loop23001.Loop2400.Add(loop24001);
            loop2000B1.Loop2300.Add(loop23001);
            loop2000A1.Loop2000B.Add(loop2000B1);

            // from here

            var loop2000B2 = new Loop_2000B_TS837P();
            loop2000B2.SubscriberHierarchicalLevel = new HL_SubscriberHierarchicalLevel();
            loop2000B2.SubscriberHierarchicalLevel.HL01 = "3";
            loop2000B2.SubscriberHierarchicalLevel.HL02 = "1";
            loop2000B2.SubscriberHierarchicalLevel.HL03 = "22";
            loop2000B2.SubscriberHierarchicalLevel.HL04 = "0";

            loop2000B2.SubscriberInformation = new SBR_SubscriberInformation();
            loop2000B2.SubscriberInformation.SBR01 = "P";
            loop2000B2.SubscriberInformation.SBR02 = "18";
            loop2000B2.SubscriberInformation.SBR09 = "12";

            loop2000B2.AllNM1 = new All_NM1_3_TS837P();
            loop2000B2.AllNM1.Loop2010BA = new Loop_2010BA_TS837P();
            loop2000B2.AllNM1.Loop2010BA.SubscriberName = new NM1_SubscriberName();
            loop2000B2.AllNM1.Loop2010BA.SubscriberName.NM101 = "IL";
            loop2000B2.AllNM1.Loop2010BA.SubscriberName.NM102 = "1";
            loop2000B2.AllNM1.Loop2010BA.SubscriberName.NM103 = "BLOGGS";
            loop2000B2.AllNM1.Loop2010BA.SubscriberName.NM104 = "FRED";
            loop2000B2.AllNM1.Loop2010BA.SubscriberName.NM108 = "MI";
            loop2000B2.AllNM1.Loop2010BA.SubscriberName.NM109 = "9876543201";

            loop2000B2.AllNM1.Loop2010BA.SubscriberAddress = new N3_AmbulanceDrop();
            loop2000B2.AllNM1.Loop2010BA.SubscriberAddress.N301 = "1 ANOTHER STR";

            loop2000B2.AllNM1.Loop2010BA.SubscriberCity = new N4_AmbulanceDrop();
            loop2000B2.AllNM1.Loop2010BA.SubscriberCity.N401 = "CHICAGO";
            loop2000B2.AllNM1.Loop2010BA.SubscriberCity.N402 = "IL";
            loop2000B2.AllNM1.Loop2010BA.SubscriberCity.N403 = "606129998";

            loop2000B2.AllNM1.Loop2010BA.SubscriberDemographicInformation = new DMG_PatientDemographicInformation();
            loop2000B2.AllNM1.Loop2010BA.SubscriberDemographicInformation.DMG01 = "D8";
            loop2000B2.AllNM1.Loop2010BA.SubscriberDemographicInformation.DMG02 = "19700601";
            loop2000B2.AllNM1.Loop2010BA.SubscriberDemographicInformation.DMG03 = "M";

            loop2000B2.AllNM1.Loop2010BB = new Loop_2010BB_TS837P();
            loop2000B2.AllNM1.Loop2010BB.PayerName = new NM1_OtherPayerName();
            loop2000B2.AllNM1.Loop2010BB.PayerName.NM101 = "PR";
            loop2000B2.AllNM1.Loop2010BB.PayerName.NM102 = "2";
            loop2000B2.AllNM1.Loop2010BB.PayerName.NM103 = "PAYER";
            loop2000B2.AllNM1.Loop2010BB.PayerName.NM108 = "PI";
            loop2000B2.AllNM1.Loop2010BB.PayerName.NM109 = "12345";

            loop2000B2.AllNM1.Loop2010BB.PayerAddress = new N3_AmbulanceDrop();
            loop2000B2.AllNM1.Loop2010BB.PayerAddress.N301 = "1 PAYER WAY";

            loop2000B2.AllNM1.Loop2010BB.PayerCity = new N4_AmbulanceDrop();
            loop2000B2.AllNM1.Loop2010BB.PayerCity.N401 = "ST LOUIS";
            loop2000B2.AllNM1.Loop2010BB.PayerCity.N402 = "MO";
            loop2000B2.AllNM1.Loop2010BB.PayerCity.N403 = "212441850";

            loop2000B2.AllNM1.Loop2010BB.AllREF = new All_REF_4_TS837P();
            loop2000B2.AllNM1.Loop2010BB.AllREF.PayerSecondaryIdentification = new List<REF_OtherPayerSecondaryIdentifier>();
            var refPayer2 = new REF_OtherPayerSecondaryIdentifier();
            refPayer2.REF01 = "2U";
            refPayer2.REF02 = "W1014";

            loop2000B2.AllNM1.Loop2010BB.AllREF.PayerSecondaryIdentification.Add(refPayer2);

            loop2000B2.Loop2300 = new List<Loop_2300_2_TS837P>();
            var loop23002 = new Loop_2300_2_TS837P();
            loop23002.ClaimInformation = new CLM_ClaimInformation();
            loop23002.ClaimInformation.CLM01 = "1001A";
            loop23002.ClaimInformation.CLM02 = "140";
            loop23002.ClaimInformation.CLM05 = new C023_HealthCareServiceLocationInformation();
            loop23002.ClaimInformation.CLM05.C02301 = "19";
            loop23002.ClaimInformation.CLM05.C02302 = "B";
            loop23002.ClaimInformation.CLM05.C02303 = "1";
            loop23002.ClaimInformation.CLM06 = "Y";
            loop23002.ClaimInformation.CLM07 = "A";
            loop23002.ClaimInformation.CLM08 = "Y";
            loop23002.ClaimInformation.CLM09 = "Y";

            loop23002.AllHI = new All_HI_2_TS837P();
            loop23002.AllHI.HealthCareDiagnosisCode = new HI_HealthCareDiagnosisCode();
            loop23002.AllHI.HealthCareDiagnosisCode.HI01 = new C022_HealthCareCodeInformation_6();
            loop23002.AllHI.HealthCareDiagnosisCode.HI01.C02201 = "ABK";
            loop23002.AllHI.HealthCareDiagnosisCode.HI01.C02202 = "I10";

            loop23002.Loop2400 = new List<Loop_2400_2_TS837P>();
            var loop24002 = new Loop_2400_2_TS837P();

            loop24002.ServiceLineNumber = new LX_ServiceLineNumber();
            loop24002.ServiceLineNumber.LX01 = "1";

            loop24002.ProfessionalService = new SV1_ProfessionalService();
            loop24002.ProfessionalService.SV101 = new C003_CompositeMedicalProcedureIdentifier_2();
            loop24002.ProfessionalService.SV101.C00301 = "HC";
            loop24002.ProfessionalService.SV101.C00302 = "99213";
            loop24002.ProfessionalService.SV102 = "140";
            loop24002.ProfessionalService.SV103 = "UN";
            loop24002.ProfessionalService.SV104 = "1";
            loop24002.ProfessionalService.SV107 = new C004_CompositeDiagnosisCodePointer();
            loop24002.ProfessionalService.SV107.C00401 = "1";

            loop24002.AllDTP = new All_DTP_2_TS837P();
            loop24002.AllDTP.Date = new DTP_Date_18();
            loop24002.AllDTP.Date.DTP01 = "472";
            loop24002.AllDTP.Date.DTP02 = "D8";
            loop24002.AllDTP.Date.DTP03 = "20151124";

            loop23002.Loop2400.Add(loop24002);
            loop2000B2.Loop2300.Add(loop23002);
            loop2000A1.Loop2000B.Add(loop2000B2);

            result.Loop2000A.Add(loop2000A1);

            return result;
        }

        /// <summary>
        /// Sample GS
        /// </summary>
        static GS CreateGs(string controlNumber)
        {
            return new GS
            {
                //  Functional ID Code
                CodeIdentifyingInformationType_1 = "IN",
                //  Application Senders Code
                SenderIDCode_2 = "RECEIVER1",
                //  Application Receivers Code
                ReceiverIDCode_3 = "SENDER1",
                //  Date
                Date_4 = DateTime.Now.Date.ToString("yyMMdd"),
                //  Time
                Time_5 = DateTime.Now.TimeOfDay.ToString("hhmm"),
                //  Group Control Number
                //  Must be unique to both partners for this interchange
                GroupControlNumber_6 = controlNumber.PadLeft(9, '0'),
                //  Responsible Agency Code
                TransactionTypeCode_7 = "X",
                //  Version/Release/Industry id code
                VersionAndRelease_8 = "005010X222A1"
            };
        }

        /// <summary>
        /// Sample ISA
        /// </summary>
        static ISA CreateIsa(string controlNumber)
        {
            return new ISA
            {
                //  Authorization Information Qualifier
                AuthorizationInformationQualifier_1 = "00",
                //  Authorization Information
                AuthorizationInformation_2 = "          ",
                //  Security Information Qualifier
                SecurityInformationQualifier_3 = "00",
                //  Security Information
                SecurityInformation_4 = "          ",
                //  Interchange ID Qualifier
                SenderIDQualifier_5 = "14",
                //  Interchange Sender
                InterchangeSenderID_6 = "RECEIVER1      ",
                //  Interchange ID Qualifier
                ReceiverIDQualifier_7 = "16",
                //  Interchange Receiver
                InterchangeReceiverID_8 = "SENDER1        ",
                //  Date
                InterchangeDate_9 = DateTime.Now.Date.ToString("yyMMdd"),
                //  Time
                InterchangeTime_10 = DateTime.Now.TimeOfDay.ToString("hhmm"),
                //  Standard identifier
                InterchangeControlStandardsIdentifier_11 = "U",
                //  Interchange Version ID
                //  This is the ISA version and not the transaction sets versions
                InterchangeControlVersionNumber_12 = "00501",
                //  Interchange Control Number
                InterchangeControlNumber_13 = controlNumber.PadLeft(9, '0'),
                //  Acknowledgment Requested (0 or 1)
                AcknowledgementRequested_14 = "1",
                //  Test Indicator
                UsageIndicator_15 = "T",
            };
        }

        static string LoadString(Stream stream)
        {
            stream.Position = 0;
            using (var reader = new StreamReader(stream, Encoding.Default))
            {
                return reader.ReadToEnd();
            }
        }
    }
}
